spring:
  datasource:
    url:
      jdbc:oracle:thin:@localhost:49161:xe
    username:
      system
    password:
      oracle
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5

togglz:
  features:
    firstFeature:
      enabled: true
      param:
        firstProperties: 35
        secondProperties: 1
    secondFeature:
      enabled: false
      param:
        firstProperties: 36
        secondProperties: 2